### ISSUE TITLE
Support WooCommerce Blocks

### ISSUE THREAD

**Issue by masteradhoc** [wallee-payment/woocommerce#23]
Currenty it seems this plugin is not yet supporting WooCommerce Blocks.
See ([Pluginrepo](https://wordpress.org/plugins/woo-gutenberg-products-block/), [GIthub](https://github.com/woocommerce/woocommerce-blocks)).

This leads to Payment Methods not showing in the modern block checkout. In the classic shortcode integration of the checkout all works as expectec.

To support Blocks check this guide: https://developer.woocommerce.com/2021/03/15/integrating-your-payment-method-with-cart-and-checkout-blocks/

Thanks.

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), I forwarded your feature request to our plugins team.

We will let you know, when we have further information about it.

Best regards

**Comment by masteradhoc** [comment]
@theodorspringwallee any update here?

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), we only can confirm this incompatibility right now.

Within the next two weeks, I should get further information from our product owners, when the compatibility development for the WooCommerce Blocks from our plugin can start.

We will let you know, when we have further information about it.

Best regards

**Comment by masteradhoc** [comment]
FYI see [the News](https://developer.woocommerce.com/2022/08/18/woocommerce-blocks-8-3-0-8-3-1-release-notes/)
"Cart and Checkout blocks are enabled and will be bundled in WooCommerce Core in WooCommerce 6.9."

**Comment by masteradhoc** [comment]
@theodorspringwallee any update?

**Comment by nielslange** [comment]
@theodorspringwallee On https://github.com/woocommerce/woocommerce-blocks/blob/trunk/docs/third-party-developers/extensibility/checkout-payment-methods/payment-method-integration.md you can find detailed information on how to make the [wallee](https://github.com/wallee-payment/woocommerce) extension compatible to [WooCommerce Blocks](https://github.com/woocommerce/woocommerce-blocks).

**Comment by masteradhoc** [comment]
@theodorspringwallee when can we get this?
![image](https://github.com/wallee-payment/woocommerce/assets/6242098/94b1ee39-2c16-4f17-a20e-be220827ad48)

**Comment by theodorspringwallee** [comment]
Dear

Our developers are working on it. Currently, we have this manual workaround:

If merchants who are using checkout blocks are experiencing issues with our payment methods not appearing, the fix is:

1.  navigate to pages → checkout → edit
2. scroll down to where the ‘payment options’ block is. click on this
3. click on the 3 vertical dots, visible at the top of the page
4. choose 'code editor.
5. Replace the contents with the following block:
```
<!-- wp:template-part {"slug":"checkout-header","theme":"woocommerce/woocommerce"} /-->
<!-- wp:group {"layout":{"inherit":true,"type":"constrained"}} -->
<div class="wp-block-group">
[woocommerce_checkout]
</div>
<!-- /wp:group -->
```
6. Click save and confirm save.
7. Exit the code editor

This will restore the old way of doing the checkout.

I hope this will help you.

Best regards

**Comment by thibault-mambour** [comment]
our latest version of the plugin is compatible with WC blocks
