### ISSUE TITLE
Plugin Closure

### ISSUE THREAD

**Issue by masteradhoc** [wallee-payment/woocommerce#24]
https://de.wordpress.org/plugins/woo-wallee/

"This plugin has been decommissioned as of 5 September 2022 and is not available for download. This decommissioning is temporary, waiting for a full review."

What happened here? When its available again?

**Comment by eightam** [comment]
I've just spoken to wallee support.
Tuesday, September 20th it should be fixed.

The reason is a fatal error when updating to woocommerce > 6.9

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), [eightam](https://github.com/eightam)

Currently, we need to fulfil some new requirements for the WordPress Marketplace.

Therefore, please use this repository to download the newest Wallee Plugin version, till our plugin is available again on the Marketplace.

I appreciate your understanding.

Best regards

**Comment by SaurabhShinx** [comment]
Hi there,

Is the plugin issue resolved for the latest woocommerce version?

**Comment by masteradhoc** [comment]
@SaurabhGtr @eightam its available again. https://de.wordpress.org/plugins/woo-wallee/
