### ISSUE TITLE
Attaching Wallee Innvoice to WooCommerce

### ISSUE THREAD

**Issue by rapsli** [wallee-payment/woocommerce#3]
I'm trying to modify the plugin so that WooCommerce is sending e-mails, but by attaching the Wallee PDF (invoice) to the WooCommerce e-mail. Can you give me a headstart on which Endpoint I would need to use?

**Comment by thomashunziker** [comment]
Dear Raphael, you can send the invoice with wallee directly. Have you tried that? If yes, you may want to point out with what you are not happy about.

The issue is that the shop email is sent before the transaction may have reached the completed state. As such you would have to delay the sending until the corresponding webhook has been delivered. This is a bit tricky.

Regards,
Thomas

**Comment by thomashunziker** [comment]
Dear Raphael,
I understand your need to delay the invoice. To setup this kind of processes I recommend to set the invoice connector use the deferred completion. There is a setting on the connector for this. The effect is the following:
- The invoice is not sent and also not created during the authorization (order creation).
- You can send the completion from within WooCommerce and adjust the line items before. E.g. when there is an item not on stock you can cancel it. Once you submit the completion the invoice will be created in wallee. Wallee can also send the invoice via email. 
- The invoice date will be the date of the completion. The payment term will start at the completion date.

Additionally you can control what email is sent. There are generally three emails:
- The email which is sent during the authorization (order creation).
- The email which is sent when the completion has been done.
- The email which is sent once the transaction has reach the fulfill state.

You can control on the connector configuration which of those emails should be sent. We normally delay the sending a bit so when we see that we would send multiple emails in a row we skip the authorization email resp. the completion email. You can also control if we should skip it or not. All those things you can setup on the connector.

The above process works also for payment methods like credit card and not only for invoice. If you can implement a process where you also be able to delay the shipment until the transaction reaches the fulfill state you can implement with the above process also bank transfer (in German 'Vorkasse').

**Comment by rapsli** [comment]
Hi Thomas
Yes I have looked into the deferred process. The thing that bugs me there is that I'm loosing some of the automation and would have to manually operate on two platforms:

1. Order on woocommerce
2. manually authorize transaction on wallee
3. process order
4. manually complete order on woocommerce

vs.
1. order on woocommerce
2. process order
3. manually complete order on woocommerce

I guess one solution would be to have a separat fulfillment portal that would list all the orders and their states. From that portal one could authorize the payment in wallee, complete order (-> set the completed state on woocommerce).

... would though mean some coding and integration work ;)

From my understanding it's not possible to set the status of an order in woocommerce to completed via wallee, right?

**Comment by thomashunziker** [comment]
Hi Raphael,
I'm not sure if I understood the issue right:
- The buyer can create the order / transaction. The buyer does not need to do anything beside go through the regular checkout process. As a merchant you do not to do anything for the authorization.
- You can complete the order from within WooCommerce. You can send the completion and adjust the line items in the WooCommerce backend. You should never need to login to wallee at all in the daily operation. See here: https://plugin-documentation.wallee.com/wallee-payment/woocommerce/1.1.10/docs/en/documentation.html#_complete_capture_an_order

At the moment we set default order statuses which we believe fits the needs of most merchants (See: https://plugin-documentation.wallee.com/wallee-payment/woocommerce/1.1.10/docs/en/resource/state_graph.svg). There are however hooks which allows you to control the status of the order depending on the transaction state. 

In a day to day operation you most likely need the following:
- A screen to find those orders which need to be checked regarding the stock. You can achieve this by filtering the orders in WooCommerce to the state 'On-Hold'. 
- A screen where you find all the orders you have to fulfill. You can get such a screen by filtering the WooCommerce orders to the status 'processing'. 

Once the shipping has been done the order will switch to the status 'Completed'.

**Comment by rapsli** [comment]
Hi Thomas
Thanks. Helps a lot. I will do some more testing -> actually I have some issues logging in to wallee. I will report back ;)

**Comment by rapsli** [comment]
Thanks Thomas
I have actually missed the button in WooCommerce that wallee adds to trigger sending the invoice!

With this I'm ready to go.
