### ISSUE TITLE
what update ?

### ISSUE THREAD

**Issue by beatoxid** [wallee-payment/woocommerce#38]
Die neue Version funktioniert schon wieder nicht.!!! 2 update !! same error !

**Comment by andrewrowanwallee** [comment]
@beatoxid Könnten Sie hier mehr Details nennen? Wie lautet die Fehlermeldung, die Sie erhalten? Wenn Sie auch einige Reproduktionsschritte angeben könnten, wäre das großartig.

**Comment by andrewrowanwallee** [comment]
@beatoxid we are closing this as we have not heard anything from you

**Comment by andrewrowanwallee** [comment]
@beatoxid We have not heard anything more so we are closing this
