### ISSUE TITLE
English text

### ISSUE THREAD

**Issue by philbraun** [wallee-payment/woocommerce#4]
Really nitpicking here, but IMHO the english text in the Wallee setup screen should read
"Send Woocommerce order email" (instead of  "Send the Woocommerce's order email")
"Allow customers to download the invoice" (no apostroph)
"Allow customers to download the packing slip." (no apostroph)

**Comment by thomashunziker** [comment]
Thank you for the proposed improvements.

We have adapted the plugin with the proposed changes. The next release will automatically include the changes.
