### ISSUE TITLE
Stop Wallee Email to Custoer

### ISSUE THREAD

**Issue by rajuodedara006** [wallee-payment/woocommerce#5]
Hello,

I Tried to stop Wallee email to send to customer when they place an order as I'm trying to manage emails because one email already sent by Woocommerce and other email from wallee i want to stop so please let me know the process how could i stop wallee email.

Thanks,

**Comment by thomashunziker** [comment]
You can disable the email sending within your space. Under the email navigation entry you can disable the sending of any email message.

**Comment by rajuodedara006** [comment]
Hello,

I'm not getting your solution. Because there is no email navigation in wallee

**Comment by thomashunziker** [comment]
I think it is better if you open a ticket with us as we could share details about your account. It has however nothing to do with the plugin as the platform is sending the email and as such your account / space has to be configured accordingly.

**Comment by rajuodedara006** [comment]
I'm Currently on your wallee panel now let me know how can i send you ticket or if it is possible please let me know how can i disable email of payment slio and invoice one which is subjected as `New Invoice for Order`

**Comment by thomashunziker** [comment]
If the email is really been sent by wallee you can disable it with the button in the screenshot:
![disable-email](https://user-images.githubusercontent.com/2227348/106509710-42b30080-64ce-11eb-932b-7cdff34765e2.png)

With this any email sending from wallee itself will be disabled. The shop my still send emails.
