### ISSUE TITLE
E_WARNING: Cannot modify header information - headers already sent (Most recent call first)

### ISSUE THREAD

**Issue by schoenico** [wallee-payment/woocommerce#6]
Is there a fix known? Or is this a common issue?
Is there an option to remove that call?

![image](https://user-images.githubusercontent.com/38050308/122676593-0236f380-d1df-11eb-8e98-082efdadc195.png)

**Comment by vttn** [comment]
Hello @schoenico 

It looks like you ran into an error somewhere during the call. Can you please open a ticket with wallee support so that we can look into the issue in detail.

Regards,

Victor
