### ISSUE TITLE
Orders won't change to processing anymore

### ISSUE THREAD

**Issue by johnrootk** [wallee-payment/woocommerce#7]
Hi there,

Since around release 1.5.4 our orders won't change to status `processing` after the payment was successful. I neared the problem down to this commit: https://github.com/wallee-payment/woocommerce/commit/0d45ca81dba8f28d152c95a05b376e344a442786#diff-49856b57d61947bf3f688209105b5afdaee2720cd0aa98a5fbd9d54077e378bdL124-L130
I don't know exactly where the problem happens.
Right now, all orders hang on `OnHold`, even when the transaction in wallee was successful, which doesn't allow us to directly see new orders and their correct status within woocommerce. 
Could you please take a look into this problem. Feel free to ask when you need more information.

Best regards,
John

**Comment by vttn** [comment]
Hello @johnrootk 

Thanks for alerting us on this issue. Can you please open a case with our Wallee Support. This was we can look at specific transactions from your shop.

All the best,

@vttn

**Comment by vttn** [comment]
@johnrootk thank you for reporting this issue. 
The solution is to 
1. delete your webhooks for the space id associated with your shop. 
2. Once you delete the webhook, please go back to your shop and click save on your wallee settings. This will our new webhooks. New order will be updated accordingly.

Regards,


@vttn
